const LN_DETAIL_LOCATION_SELECTOR = '.sub-nav-cta__meta-text';
const LN_DETAIL_JOBTITLE_SELECTOR = '.sub-nav-cta__header';
const LN_DETAIL_COMPANY_SELECTOR = '.sub-nav-cta__optional-url';
const LN_DETAIL_POSTEDAGO_SELECTOR = '.posted-time-ago__text';
const LN_DETAIL_NOFAPPLICANTS_SELECTOR = '.num-applicants__caption';
const LN_DETAIL_ADCONTENT_SELECTOR = '.show-more-less-html__markup';
const LN_DETAIL_JOBPROPS_SELECTOR = '.description__job-criteria-text--criteria';

const LN_AD_JOB_AD_SELECTOR = 'li';
const LN_AD_JOB_LINK_SELECTOR = '.base-card__full-link';
const LN_AD_JOB_LINK_PROPS = ['name', 'href'];
const LN_AD_JOB_TITLE_SELECTOR = '.base-search-card__title';
const LN_AD_COMPANY_NAME_SELECTOR = '.base-search-card__subtitle';
const LN_AD_LOCATION_SELECTOR = '.job-search-card__location';
const LN_AD_SALARYINFO_SELECTOR = '.job-search-card__salary-info';
const LN_AD_LISTEDDATES_SELECTOR = '.job-search-card__listdate';
const LN_AD_LISTEDDATES_PROPS = ['name', 'datetime'];

const INDEED_JOBLINK_SELECTOR = 'job-link';
const INDEED_JOBTITLE_SELECTOR = 'job-title';
const INDEED_COMPANYNAME_SELECTOR = 'company-name';
const INDEED_LOCATION_SELECTOR = 'company-location';
const INDEED_JOBDESCRIPTION_SELECTOR = 'job-snippet';
const INDEED_JOBSALARY_SELECTOR = 'job-salary';
const INDEED_POSTDATE_SELECTOR = 'post-date';

const NO_APPLICANTS = 'No applicants yet';
const APPLICANT_DATA_UNKNOWN = 'Data on applicants is unknown';
const UNDISCLOSED_SALARY = 'Undisclosed';
const INDEED = "INDEED";
const LINKEDIN = "LINKEDIN";

module.exports = {
    LN_DETAIL_LOCATION_SELECTOR: LN_DETAIL_LOCATION_SELECTOR,
    LN_DETAIL_JOBTITLE_SELECTOR: LN_DETAIL_JOBTITLE_SELECTOR,
    LN_DETAIL_COMPANY_SELECTOR: LN_DETAIL_COMPANY_SELECTOR,
    LN_DETAIL_POSTEDAGO_SELECTOR: LN_DETAIL_POSTEDAGO_SELECTOR,
    LN_DETAIL_NOFAPPLICANTS_SELECTOR: LN_DETAIL_NOFAPPLICANTS_SELECTOR,
    LN_DETAIL_ADCONTENT_SELECTOR: LN_DETAIL_ADCONTENT_SELECTOR,
    LN_DETAIL_JOBPROPS_SELECTOR: LN_DETAIL_JOBPROPS_SELECTOR,

    LN_AD_JOB_AD_SELECTOR: LN_AD_JOB_AD_SELECTOR,
    LN_AD_JOB_LINK_SELECTOR: LN_AD_JOB_LINK_SELECTOR,
    LN_AD_JOB_LINK_PROPS: LN_AD_JOB_LINK_PROPS,
    LN_AD_JOB_TITLE_SELECTOR: LN_AD_JOB_TITLE_SELECTOR,
    LN_AD_COMPANY_NAME_SELECTOR: LN_AD_COMPANY_NAME_SELECTOR,
    LN_AD_LOCATION_SELECTOR: LN_AD_LOCATION_SELECTOR,
    LN_AD_SALARYINFO_SELECTOR: LN_AD_SALARYINFO_SELECTOR,
    LN_AD_LISTEDDATES_SELECTOR: LN_AD_LISTEDDATES_SELECTOR,
    LN_AD_LISTEDDATES_PROPS: LN_AD_LISTEDDATES_PROPS,

    INDEED_JOBLINK_SELECTOR: INDEED_JOBLINK_SELECTOR,
    INDEED_JOBTITLE_SELECTOR: INDEED_JOBTITLE_SELECTOR,
    INDEED_COMPANYNAME_SELECTOR: INDEED_COMPANYNAME_SELECTOR,
    INDEED_LOCATION_SELECTOR: INDEED_LOCATION_SELECTOR,
    INDEED_JOBDESCRIPTION_SELECTOR: INDEED_JOBDESCRIPTION_SELECTOR,
    INDEED_JOBSALARY_SELECTOR: INDEED_JOBSALARY_SELECTOR,
    INDEED_POSTDATE_SELECTOR: INDEED_POSTDATE_SELECTOR,

    NO_APPLICANTS: NO_APPLICANTS,
    APPLICANT_DATA_UNKNOWN: APPLICANT_DATA_UNKNOWN,
    UNDISCLOSED_SALARY: UNDISCLOSED_SALARY,
    INDEED: INDEED,
    LINKEDIN: LINKEDIN
}
